"""empty message

Revision ID: b87b8ee8f803
Revises: 
Create Date: 2021-12-09 14:11:23.418661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b87b8ee8f803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('statestable')
    op.drop_table('inserttable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inserttable',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machineid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stateid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statechange', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unixtime', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extras', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('statestable',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('string', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
